interface Producto {
    id: number;
    title: string;
    precio: number;
    cantidad: number;
}

/* API */

/* GET producto */
// Generated by https://quicktype.io

interface APIProducto {
    success: boolean;
    producto: Producto;
}

interface Producto {
    id: number;
    title: string;
    precio: number;
    cantidad: number;
}

export { type Producto, type APIProducto };
